### ISSUE TITLE
How to make jdtls recognize path to extra .jar files?

### ISSUE THREAD

**Issue by plt3** [eruizc-dev/jdtls-launcher#13]
First of all, thank you very much for this project; it's been extremely useful! I'm not entirely sure if this issue is related to how this project runs the server or just jdtls in general, so please let me know if I should be asking somewhere else.

Essentially, after installing jdtls using this project (on macOS Monterey 12.1), I successfully configured it to work with Neovim (version 0.6.1). However, jdtls signals many errors when I open up a file full of JUnit unit tests, since it does not recognize that I have installed the JUnit .jar file.

I have downloaded junit-platform-console-standalone-1.8.2.jar from https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.8.2/, and have added it to my classpath with `export CLASSPATH=".:/path/to/junit-platform-console-standalone-1.8.2.jar"`, so I can compile a file of JUnit tests with `javac MyTests.java` (and can run the tests with `java -jar /path/to/junit-platform-console-standalone-1.8.2.jar -cp . --select-class MyTests`). However, when I open up MyTests.java in Neovim, I get many errors like "The import org.junit cannot be resolved", etc. How can I point jdtls to the JUnit .jar file I have installed?

My (trimmed down) configuration using nvim-lspconfig looks like this:
```lua
local nvim_lsp = require('lspconfig')

nvim_lsp["jdtls"].setup {
  cmd = { 'jdtls' },
  init_options = {bundles = { "/path/to/junit-platform-console-standalone-1.8.2.jar" }},
  root_dir = function(fname)
     return require'lspconfig'.util.root_pattern('pom.xml', 'gradle.build', '.git')(fname) or vim.fn.getcwd()
  end
}
```

As you can see, I have tried to point jdtls to the JUnit .jar file with init_options.bundles, but this doesn't seem to make any difference. I surely need to specify the path to the JUnit .jar file in some other manner, but I am not sure where to go from here. The only other source I could find from my research was https://stackoverflow.com/questions/66487382/nightly-build-of-neovim-with-jdtls-java-language-server-not-recognizing-jar-fi, but I wasn't able to make much sense of the answer.

Any help would be appreciated!

**Comment by eruizc-dev** [comment]
Hi! Thanks for your words, I really appreciate them ^^

The stackoverflow post seems missleading, it only says how to get jdt running with a minimal shell script (basically what this tool does). It doesn't do anything for imports.

Without putting much thought into this what I'd try is putting the jar in `~/.m2/org/junit/1.8.2/junit-platrofm-console-standalone-1.8.2.jar` which is where all maven dependencies are installed. Maybe jdt.ls will search for it in there.

Notify me if that doesn't work and I'll look further into it

**Comment by plt3** [comment]
Thanks for such a quick response! I tried your solution, but unfortunately no luck. I tried putting the `junit-platform-console-standalone-1.8.2.jar` file in `~/.m2/repository/junit/junit/3.8.2` (this and 3.8.1 were the only two subdirectories of ~/.m2 that resembled the path you gave me) but the warnings kept showing up in Neovim even if I tried adding that path to the init_options.bundles array. I also tried putting the .jar file in the exact path you gave me (using `mkdir -p ~/.m2/org/junit/1.8.2/`) but that did not change anything. Let me know if you have any other ideas!

**Comment by eruizc-dev** [comment]
I got some info that might be useful, here's an issue about this in jdtl.ls project: <https://github.com/eclipse/eclipse.jdt.ls/issues/1986>

Basically what it says is that you can create a `.classpath` file in the root of the project and configure it following [this documentation](https://programmer.group/detailed-explanation-of-classpath-file-in-eclipse-project.html). Entry 3.4 describes using dependencies (kind = lib).

Hope that works!

**Comment by eruizc-dev** [comment]
I'm glad it helped and you finally figured it out!

Happy codding

**Comment by idr4n** [comment]
I was struggling to set this up using nvim-jdtls and finally got it to work without the need to manually change the individual project workspace .classpath file. Basically, in the nvim-jdtls config, I reference the libraries I need like this:

```lua
local config = {
    ...
    settings = {
        java = {
	    project = {
                referencedLibraries = { "path_to_jar", },
	    },
        },
    },
}

require("jdtls").start_or_attach(config)
```
