### ISSUE TITLE
Download from eclipse doesn't work any more

### ISSUE THREAD

**Issue by yngwi** [eruizc-dev/jdtls-launcher#9]
The download of the language server from eclipse doesn't work any more, it probably got moved somewhere and the original link redirects. To have the installation work again, the `-L` flag has to be added to the respective curl calls. I did it [here](https://github.com/yngwi/jdtls-launcher/blob/a85176df667d17a9161cb99918cfdbafedf9b41e/jdtls-launcher.sh#L78) and [here](https://github.com/yngwi/jdtls-launcher/blob/a85176df667d17a9161cb99918cfdbafedf9b41e/jdtls-launcher.sh#L84) in my fork of your repository although I didn't try if the second one was necessary.

**Comment by eruizc-dev** [comment]
Didn't have the time to test this, do you mind opening a [PR](https://github.com/eruizc-dev/jdtls-launcher/compare) I can review later?

**Comment by eruizc-dev** [comment]
Thank you for detecting this and making the PR @yngwi

**Comment by yngwi** [comment]
You're welcome. Thanks for making the repository :)
